language: dart
dart: stable

script: ./tool/travis.sh

# Speed up builds by using containerization. Disable this if you need to use
# sudo in your scripts.
sudo: false

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d01aa607aab004a51594
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
